### PR TITLE
Code improvements.

### PR DESCRIPTION
**Pull request by amitness**
I've removed the semicolon which was causing error on Python 2. Also removed double import OS statements.

### CODE REVIEW

**Comment by yask123** [comment]
Thanks for helping. :smile: 
Could you merge all those commits into a single commit ?

**Comment by amitness** [comment]
Sorry but how do I do that?

**Comment by amitness** [comment]
I tried some suggestions on the internet but couldn't quite figure out how to merge multiple commits into one. Help me if you can.

**Comment by yask123** [comment]
http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Pull request closed without merging**
